list: $/martinimultimedia/press/models/release/columns.yaml
modelClass: MartiniMultimedia\Press\Models\Release
title: Releases
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/press/releases/update/:id'
